---
timeout: 180
instances: 1
memory: 512M
#buildpack: toms-java-buildpack
env:
    SPRING_PROFILES_DEFAULT: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: config-server
  path: configServer/target/configServer-0.0.1-SNAPSHOT.jar
#  random-route: true
  hosts:
    - config-server-20150731
